const mongoose = require('mongoose');

const liquidacionSchema = new mongoose.Schema({
  idLiquidacion: { type: String, required: true, unique: true },
  email: { type: String, required: true },
  nombre: { type: String },
  documento: { type: String },
  cargo: { type: String },
  tipoContrato: { type: String },
  fechaIngreso: { type: Date },
  fechaLiquidacion: { type: Date, required: true },
  fechaGeneracion: { type: Date, default: Date.now },
  motivoRetiro: { type: String },
  diasTrabajados: { type: Number },
  diasTrabajadosBrutos: { type: Number },
  diasMesActual: { type: Number },
  diasMesEfectivos: { type: Number },
  diasYaPagados: { type: Number },
  inasistencias: { type: Number },
  inasistenciasCalculado: { type: Number },
  inasistenciasManual: { type: Boolean },
  vacacionesTomadas: { type: Number },
  vacacionesTomadasAuto: { type: Number },
  vacacionesTomadasManual: { type: Boolean },
  salarioBase: { type: Number },
  auxilioTransporte: { type: Number },
  baseLiquidacion: { type: Number },
  sueldoPendiente: { type: Number },
  auxilioPendiente: { type: Number },
  totalReintegros: { type: Number },
  prima: { type: Number },
  cesantias: { type: Number },
  interesesCesantias: { type: Number },
  vacaciones: { type: Number },
  totalPrestaciones: { type: Number },
  indemnizacion: { type: Number, default: 0 },
  saludEmpleado: { type: Number },
  pensionEmpleado: { type: Number },
  deduccionExamenMedico: { type: Number },
  otrasDeducciones: { type: Number },
  totalDeducciones: { type: Number },
  detalleDeducciones: [{
    tipo: String,
    descripcion: String,
    valorTotal: Number,
    cuotasPagadas: Number,
    cuotasTotal: Number,
    saldoPendiente: Number
  }],
  tieneNominaPagada: { type: Boolean },
  nominaReferencia: { type: String },
  totalLiquidacion: { type: Number },
  generadoPor: { type: String },
  estado: { type: String, enum: ['activa', 'anulada'], default: 'activa' }
}, { timestamps: true });

module.exports = mongoose.model('Liquidacion', liquidacionSchema);